@startuml
left to right direction

skin rose

actor :Klient: as client
actor :Trener: as coach
actor :Pracownik: as worker 
actor :Menadżer: as manager

"Kup karnet" as (buySubscription)
"Anuluj karnet" as (cancelSubscription)
"Przekaż karnet na innego klienta" as (passSubscription)

client -- (buySubscription)
client -- (cancelSubscription)
client -- (passSubscription)


@enduml