@startuml "Wykupienie karnetu"
title "Wykupienie karnetu"

|k| klient
|p| pracownik
|s| system

|k|
start
floating note left: Pracownik musi być zalogowany w systemie
:Prośba o utworzenie karnetu;

|p|
:Wybór opcji "Nowy karnet";

|s|
repeat
repeat
:Wyświetlenie formularza;

|p|
:Wprowadzenie danych personalnych, płatniczych i kontaktowych;
:Zatwierdzenie operacji;

if (Operacja zatwierdzona?) then (tak)
else (nie)
stop
endif

|s|
:Sprawdzenie formatu danych;
repeat while (Poprawny format danych?) is (nie) not (tak)
:Sprawdzenie dostępności metody płatniczej;
repeat while (Metoda płatnicza dostępna?) is (nie) not (tak)
:Utworzenie karnetu;
:Pobranie opłaty;
:Wysłanie loginu i tymczasowego hasła do klienta;
:Wyświetenie potwierdzenia;

stop
floating note left: Utworzenie karnetu identyfikującego użytkownika
@enduml