@startuml "Wykupienie karnetu"
title "Wykupienie karnetu"

|k| klient
|p| pracownik
|s| system

|k|
start
floating note left: Pracownik musi być zalogowany w systemie
:Prośba o utworzenie karnetu;

|p|
:Wybór opcji "Nowy karnet";

|s|
:Wyświetlenie formularza;

|p|
:Wprowadzenie danych personalnych, płatniczych i kontaktowych;

if (Zatwierdzenie operacji) then (tak)
|s|
:Sprawdzenie formatu danych;
:Sprawdzenie dostępności metody płatniczej;
:Utworzenie karnetu;
:Pobranie opłaty;
:Wysłanie loginu i tymczasowego hasła do klienta;
:Wyświetenie potwierdzenia;
else (nie)
:Anuluj operację;
stop
endif

stop
floating note left: Utworzenie karnetu identyfikującego użytkownika

@enduml