@startuml
note "Diagram zawiera jedynie elementy należące do wzorca." as n

enum MembershipType {
    STANDARD,
    PREMIUM,
    MULTI_SPORT
}

abstract class Membership {
    + {abstract} getValidityTime(): unsigned int
    + {abstract} getChargePrice(): float
}

class MultisportMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

MultisportMembership <|-- Membership

class StandardMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

StandardMembership <|-- Membership

class PremiumMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

PremiumMembership <|-- Membership

Worker .right.> MembershipType

class Worker {
    + createMembership(type: MembershipType): Membership
}

Worker .left.> Membership
@enduml
