@startuml
|s|system
|k|kierownik

start 
floating note left: Sala musi istnieć w systemie
:Menadzer wybiera opcję Wyświetl sale treningowe;
repeat
    repeat
        |s|
        :Wyświetl listę z salami;
        |k|
        :Wpisanie numeru sali do wyszukiwarki;
        |s|
        :Wyświetlenie opcji pasującej do wyszukiwania;
        |k|
        :Wybranie sali;
        |s|
        :Wyświetl informacje o sali;
    repeat while (Istnieją sale otwarte?) is (nie) not (tak)
    :Wyświetlenie listy dostępnych sal;
    |k|
    :Wybranie dostępnej sali;
    :Wybranie opcji "Zamknij salę";
    |s|
    :Wyświetlenie okna potwierdzenia;
    |k|
repeat while (Potwierdzenie wyboru?) is (nie) not (tak)
    |s|
    :Zmiana statusu sali;
    :Wygenerowanie potwierdzenia operacji;
stop
floating note left: Status sali ustawiony na Zamknieta

@enduml
