@startuml
enum MembershipType {
    STANDARD,
    PREMIUM,
    MULTISPORT
}

class Membership {
    + extend(days: unsigned int)
    + isValid(): bool
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

class MultisportMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

MultisportMembership <|-- Membership

class StandardMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

StandardMembership <|-- Membership

class PremiumMembership {
    + getValidityTime(): unsigned int
    + getChargePrice(): float
}

PremiumMembership <|-- Membership

class Client {
    - weight: float
    - height: float
    - birthTimeStamp: unsigned int
    - membership: Membership
    + getAvailableTrainingSessions(): List<TrainingSession>
    + getDoneTrainingSessions(): List<TrainingSession>
    + resignFromTraining(trainingSession: TrainingSession): bool
    + signUpForTraining(trainingSession: TrainingSession): bool
}

Worker .left.> MembershipType

class Worker {
    + cancelMembership(client: Client): bool
    + createMembership(type: MembershipType): Membership
    + editUserData(user: User): bool
    + scheduleMaintenance(gym: Gym): void
    + finishMaintenance(gym: Gym): void
}

Worker -.> Client
Worker .> Membership

Membership <--* Client
@enduml
