@startuml

top to bottom direction
skinparam linetype ortho

class TrainingResourceManager {
  - TrainingResourceManager(): 
  - instance: TrainingResourceManager
  - availableResources: List<Resource>
  + getInstance(): TrainingResourceManager
  + allocateResource(Resource): boolean
  + releaseResource(Resource): void
}

TrainingResourceManager -.> TrainingResourceManager : <<create>>
TrainingResourceManager o--> TrainingResourceManager : instance

@enduml
