@startuml "Message adapters"

class User{
  + {static} sendMessage(Message)
}


interface MessageService{
  + sendMessage(message: Message): bool
}


User -.> MessageService : "uses"

class MessangerMessageAdapter{
  
}

MessangerMessageAdapter -.|> MessageService : "Implements"
MessangerMessageAdapter -.-> MessengerMessangeService : "Uses"

class MessengerMessangeService{
  + sendMessage(from: Long, to: Long, title: String, content: String)
}
note left
External service / interface
end note

class DiscordMessangeService{
  + sendMessage(from: Long, to: Long, message: String)
}

note right
External service / interface
end note

DiscordMessageAdapter -.|> MessageService : "Implements"
DiscordMessageAdapter -.-> DiscordMessangeService : "Uses"

note "Diagram zawiera jedynie\nelementy należące do wzorca." as n

@enduml