

@startuml

actor Client as Clienta
participant GUI
participant TrainingSession
participant Client as Client


Clienta -> GUI: signupForTraining()
GUI -> TrainingSession: signupForTraining()
TrainingSession -> Client: hasValidMembership()

alt has valid membership
    Client --> TrainingSession 
    TrainingSession -> TrainingSession: Add to attendants list
    TrainingSession --> GUI
    GUI --> Client
else does not have membership
    Client --> TrainingSession
    TrainingSession --> GUI 
    GUI --> Clienta
end

@enduml

