@startuml

title Analiza postępów Klienta przez Trenera : Damian Karwat
|s| System
|t| Trener
start
floating note left: Trener zalogowany w systemie
floating note left: W systemie istnieje Klient
:przejście do sekcji Organizacja zajęć w systemie;
|s|
:Wyświetlenie kalendarza zajęć;
|t|
:Wybór zajęć;
repeat:
    :Wybranie opcji lista zapisanych Klientów;
    |s|
repeat while (Czy na liście istnieje chociaż jeden Klient?) is (nie) not (tak)
:Wyświetlenie listy zapisanych Klientów;
|t|
:Wybranie jednego z Klientów;
repeat
|s|
:Wyświetlenie profilu Klienta;
|t|
:Wybór opcji statystyki Klienta;
|s|
repeat while (Dane na temat postępów Klienta znajdują się w systemie?) is (nie) not (tak)
:Wyświetlenie danych i statystyk Klienta;
stop
floating note left: Uzyskany dostęp do szczegółowych statystyk postępów klienta

@enduml
