

@startuml create_exercise
actor Trainer
participant GUI
participant ExerciseService
participant DB as "Database"
participant Exercise

Trainer -> GUI : createExercise()
GUI -> ExerciseService : createExercise()

ExerciseService -> DB : checkIfExerciseExists()
alt exercise does not exist
    DB --> ExerciseService
    ExerciseService -> Exercise : <<create>>
    Exercise -> ExerciseService
    ExerciseService -> DB : saveExercise()
    DB --> ExerciseService
    ExerciseService --> GUI : exerciseCreated()
    GUI --> Trainer
else exercise already exists

    opt edit exercise
        Trainer -> GUI : editExercise()
        GUI -> ExerciseService : updateExercise()
        ExerciseService -> DB : saveExercise()
        DB --> ExerciseService
        ExerciseService --> GUI : exerciseUpdated()
        GUI --> Trainer
    end
    ExerciseService --> GUI 
    GUI --> Trainer
end
@enduml

